<div class="blueRule"><!-- empty --></div>
<h1>Information for Users</h1>
<div class="textContent">
	<p><span class="blueText"><i><b>Tips on searching</b></i></span> – To find data of interest, consider entering into the search field (upper right corner of home page) combinations of key words of interest in your sample construction. For instance, you might be interested in seeing the Museum of Comparative Zoology’s holdings of skulls of the genus <i>Alouatta</i> (howler monkeys).  In that case, you might type in “MCZ skull Alouatta".  This will return a list of media files and specimens that meet these criteria.  If a search returns no results consider modifying your search terms slightly.  For instance try replacing “skull" with “cranium".</i>
	<p><span class="blueText"><i><b>Use the media cart</b></i></span> – After running a search you may see several specimens or <b>media</b> files of interest. Instead of downloading each one individually, we suggest adding files to your media cart.  This can only be done with results organized by <b>media</b> (i.e., a <b>user</b> cannot add all the available records for a given specimen automatically. They would have to go into the specimen record and select which <b>media</b> files were of interest).  You must be logged in to have access to the media cart.</p>
	<p><span class="blueText"><i><b>Batch downloads</b></i></span> – Once you have added all of the media files of interest to your media cart, click on your cart and select batch download, and walk away while the data downloads.  When the batch download is complete you will find, in addition to your <b>media</b>, a metadata list including repository information (e.g. taxonomy, element description, and specimen numbers), digitization information (e.g., scanner facility, scanner type, resolution, and energy settings), and citation information (e.g., copyright status, citation instructions, and grant citation instructions).</p>
	<p><span class="blueText"><i><b>Make data lists</b></i></span> – <b>Users</b> may not be interested in immediately downloading all data files in their cart. However, since the media cart is linked to their MorphoSource account, the contents of their cart will stil be available on subsequent site visits. Alternatively they can download a metadata file with a list of the selected media only.</p>

</div>
